# Filtering stop data 
(Just using Eagles data for now)

In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv("pa_philadelphia_2020_04_01.csv")
data

/tmp/ipykernel_653986/995676016.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("pa_philadelphia_2020_04_01.csv")

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,arrest_made,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband
0,411981,2014-01-01,01:14:00,NaN,NaN,NaN,19.0,191,31.0,black,...,True,arrest,True,False,True,True,False,Black - Non-Latino,True,False
1,407442,2014-01-01,01:57:00,NaN,NaN,NaN,12.0,121,21.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
2,217556,2014-01-01,03:30:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,24.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
3,217557,2014-01-01,03:40:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,20.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
4,230988,2014-01-01,08:30:00,N 56TH ST / UPLAND WAY,39.983712,-75.234188,19.0,193,31.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,1791698,2018-04-14,21:36:00,S 59TH ST / ELMWOOD AV,39.928084,-75.221956,12.0,123,60.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1865092,1789312,2018-04-14,22:01:00,2600 BLOCK JUDSON ST,39.998242,-75.175190,39.0,393,33.0,asian/pacific islander,...,False,NaN,NaN,False,False,False,False,Asian,False,False
1865093,1791237,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,21.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
1865094,1791243,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,22.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
1865095,1791232,2018-04-14,23:10:00,200 BLOCK W LEHIGH AV,39.991461,-75.134880,25.0,253,69.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False

In [3]:
eagles = pd.read_csv("EAGLES_SCHEDULE_CLEANED.csv")
eagles

,Season,Year,Week,Day,FullDate,FullTime,Home,Opp,W,TeamScore,OppScore,Differential
0,2014,2014,1,Sun,2014-09-07,13:02:00,0,Jacksonville Jaguars,1,34.0,17.0,17.0
1,2014,2014,2,Mon,2014-09-15,20:31:00,1,Indianapolis Colts,1,30.0,27.0,3.0
2,2014,2014,3,Sun,2014-09-21,13:02:00,0,Washington Redskins,1,37.0,34.0,3.0
3,2014,2014,4,Sun,2014-09-28,16:25:00,1,San Francisco 49ers,0,21.0,26.0,-5.0
4,2014,2014,5,Sun,2014-10-05,13:02:00,0,St. Louis Rams,1,34.0,28.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...
80,2018,2018,15,Sun,2018-12-16,20:20:00,1,Los Angeles Rams,1,30.0,23.0,7.0
81,2018,2018,16,Sun,2018-12-23,13:00:00,0,Houston Texans,1,32.0,30.0,2.0
82,2018,2018,17,Sun,2018-12-30,16:25:00,1,Washington Redskins,1,24.0,0.0,24.0
83,2018,2019,Wild Card,Sun,2019-01-06,16:40:00,1,Chicago Bears,1,16.0,15.0,1.0
84,2018,2019,Division,Sun,2019-01-13,16:40:00,1,New Orleans Saints,0,14.0,20.0,-6.0

In [5]:
eagles.dtypes, data.dtypes

(Season            int64
 Year              int64
 Week             object
 Day              object
 FullDate         object
 FullTime         object
 Home              int64
 Opp              object
 W                 int64
 TeamScore       float64
 OppScore        float64
 Differential    float64
 dtype: object,
 raw_row_number                object
 date                          object
 time                          object
 location                      object
 lat                          float64
 lng                          float64
 district                     float64
 service_area                  object
 subject_age                  float64
 subject_race                  object
 subject_sex                   object
 type                          object
 arrest_made                     bool
 outcome                       object
 contraband_found              object
 frisk_performed                 bool
 search_conducted                bool
 search_person                   bool
 search_vehicle                  bool
 raw_race                      object
 raw_individual_contraband       bool
 raw_vehicle_contraband          bool
 dtype: object)

In [ ]:
# convert to datetime cols
eagles["FullDate"] = pd.to_datetime(eagles["FullDate"])
data["date"] = pd.to_datetime(data["date"])

In [14]:
mask = data["date"].isin(eagles["FullDate"].unique())
eagles_gamedays = data[mask]
eagles_gamedays

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,arrest_made,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband
266256,125049,2014-09-07,00:00:00,100 BLOCK GRAPE ST,40.026767,-75.221397,5.0,052,21.0,white,...,False,NaN,NaN,False,False,False,False,White - Non-Latino,False,False
266257,339230,2014-09-07,00:00:00,1100 BLOCK W ROCKLAND ST,40.027025,-75.142747,35.0,352,25.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
266258,339231,2014-09-07,00:00:00,1100 BLOCK W ROCKLAND ST,40.027025,-75.142747,35.0,352,25.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
266259,290864,2014-09-07,00:00:00,900 BLOCK E TIOGA ST,40.001047,-75.112250,24.0,241,28.0,hispanic,...,False,NaN,NaN,False,False,False,False,White - Latino,False,False
266260,311129,2014-09-07,00:01:00,1300 BLOCK W WILLIAM ST,39.996231,-75.151839,25.0,254,24.0,white,...,False,NaN,NaN,False,False,False,False,White - Non-Latino,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792706,1680123,2018-02-04,23:22:00,3300 BLOCK RIDGE AV,39.993029,-75.186268,22.0,222,51.0,black,...,True,arrest,True,False,True,True,False,Black - Non-Latino,True,False
1792707,1684090,2018-02-04,23:26:00,N BROAD ST / RACE ST,39.956259,-75.162821,3.0,31,23.0,black,...,False,NaN,False,True,True,False,True,Black - Non-Latino,False,False
1792708,1679824,2018-02-04,23:43:00,N 52ND ST / WYALUSING AV,39.969527,-75.225375,19.0,192,48.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1792709,1680122,2018-02-04,23:45:00,1000 BLOCK N DELAWARE AV,39.964607,-75.134133,26.0,263,30.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1792710,1681333,2018-02-04,23:53:00,S 54TH ST / LOCUST ST,39.956289,-75.229527,18.0,182,53.0,black,...,True,arrest,NaN,True,False,False,False,Black - Non-Latino,False,False

In [15]:
eagles_home_games = eagles[eagles["Home"] == 1]
eagles_home_games

,Season,Year,Week,Day,FullDate,FullTime,Home,Opp,W,TeamScore,OppScore,Differential
1,2014,2014,2,Mon,2014-09-15,20:31:00,1,Indianapolis Colts,1,30.0,27.0,3.0
3,2014,2014,4,Sun,2014-09-28,16:25:00,1,San Francisco 49ers,0,21.0,26.0,-5.0
6,2014,2014,8,Sun,2014-10-26,16:05:00,1,Arizona Cardinals,0,20.0,24.0,-4.0
7,2014,2014,9,Sun,2014-11-02,13:03:00,1,Houston Texans,1,31.0,21.0,10.0
9,2014,2014,11,Sun,2014-11-16,16:25:00,1,Green Bay Packers,0,20.0,53.0,-33.0
11,2014,2014,13,Thu,2014-11-27,16:36:00,1,Dallas Cowboys,1,33.0,10.0,23.0
14,2014,2014,16,Sat,2014-12-20,16:30:00,1,Washington Redskins,0,24.0,27.0,-3.0
15,2014,2014,17,Sun,2014-12-28,13:02:00,1,New York Giants,1,34.0,26.0,8.0
16,2015,2015,1,Mon,2015-09-14,19:10:00,1,Atlanta Falcons,0,24.0,26.0,-2.0
18,2015,2015,3,Sun,2015-09-27,13:03:00,1,New York Jets,1,24.0,17.0,7.0
19,2015,2015,4,Sun,2015-10-04,13:03:00,1,Washington Redskins,0,20.0,23.0,-3.0
22,2015,2015,7,Sun,2015-10-25,20:31:00,1,Carolina Panthers,0,16.0,27.0,-11.0
23,2015,2015,9,Sun,2015-11-08,20:31:00,1,Dallas Cowboys,1,33.0,27.0,6.0
26,2015,2015,12,Thu,2015-11-26,12:35:00,1,Detroit Lions,0,14.0,45.0,-31.0
27,2015,2015,13,Sun,2015-12-06,16:25:00,1,New England Patriots,1,35.0,28.0,7.0
31,2015,2016,17,Sun,2016-01-03,13:03:00,1,New York Giants,1,35.0,30.0,5.0
33,2016,2016,2,Mon,2016-09-19,20:30:00,1,Chicago Bears,1,29.0,14.0,15.0
35,2016,2016,5,Sun,2016-10-09,13:02:00,1,Detroit Lions,0,23.0,24.0,-1.0
36,2016,2016,6,Sun,2016-10-16,13:03:00,1,Washington Redskins,0,20.0,27.0,-7.0
38,2016,2016,8,Sun,2016-10-30,20:31:00,1,Dallas Cowboys,0,23.0,29.0,-6.0
39,2016,2016,9,Sun,2016-11-06,13:00:00,1,New York Giants,0,23.0,28.0,-5.0
41,2016,2016,11,Sun,2016-11-20,16:25:00,1,Seattle Seahawks,0,15.0,26.0,-11.0
43,2016,2016,13,Sun,2016-12-04,13:00:00,1,Cincinnati Bengals,0,14.0,32.0,-18.0
45,2016,2016,15,Sun,2016-12-18,13:00:00,1,Baltimore Ravens,0,26.0,27.0,-1.0
48,2017,2017,1,Sun,2017-09-10,13:00:00,1,Washington Redskins,1,30.0,17.0,13.0
49,2017,2017,2,Sun,2017-09-17,13:00:00,1,Kansas City Chiefs,0,20.0,27.0,-7.0
51,2017,2017,4,Sun,2017-10-01,16:05:00,1,Los Angeles Chargers,1,26.0,24.0,2.0
53,2017,2017,6,Thu,2017-10-12,20:25:00,1,Carolina Panthers,1,28.0,23.0,5.0
57,2017,2017,11,Sun,2017-11-19,20:30:00,1,Dallas Cowboys,1,37.0,9.0,28.0
59,2017,2017,13,Sun,2017-12-03,20:30:00,1,Seattle Seahawks,0,10.0,24.0,-14.0
60,2017,2017,14,Sun,2017-12-10,16:25:00,1,Los Angeles Rams,1,43.0,35.0,8.0
61,2017,2017,15,Sun,2017-12-17,13:00:00,1,New York Giants,1,34.0,29.0,5.0
68,2018,2018,2,Sun,2018-09-16,13:00:00,1,Tampa Bay Buccaneers,0,21.0,27.0,-6.0
70,2018,2018,4,Sun,2018-09-30,13:00:00,1,Tennessee Titans,0,23.0,26.0,-3.0
72,2018,2018,6,Thu,2018-10-11,20:20:00,1,New York Giants,1,34.0,13.0,21.0
74,2018,2018,8,Sun,2018-10-28,09:30:00,1,Jacksonville Jaguars,1,24.0,18.0,6.0
76,2018,2018,11,Sun,2018-11-18,16:25:00,1,New Orleans Saints,0,7.0,48.0,-41.0
79,2018,2018,14,Sun,2018-12-09,16:25:00,1,Dallas Cowboys,0,23.0,29.0,-6.0
80,2018,2018,15,Sun,2018-12-16,20:20:00,1,Los Angeles Rams,1,30.0,23.0,7.0
82,2018,2018,17,Sun,2018-12-30,16:25:00,1,Washington Redskins,1,24.0,0.0,24.0
83,2018,2019,Wild Card,Sun,2019-01-06,16:40:00,1,Chicago Bears,1,16.0,15.0,1.0
84,2018,2019,Division,Sun,2019-01-13,16:40:00,1,New Orleans Saints,0,14.0,20.0,-6.0

In [16]:
mask2 = data["date"].isin(eagles_home_games["FullDate"].unique())
eagles_home_gamedays = data[mask2]
eagles_home_gamedays

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,arrest_made,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband
276772,216366,2014-09-15,00:00:00,1200 BLOCK S 26TH ST,39.938690,-75.186919,17.0,172,32.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
276773,320076,2014-09-15,00:00:00,2600 BLOCK N FRONT ST,39.989349,-75.131270,26.0,261,24.0,white,...,False,NaN,NaN,False,False,False,False,White - Non-Latino,False,False
276774,205399,2014-09-15,00:00:00,4400 BLOCK FRANKFORD AV,40.012579,-75.087572,15.0,151,38.0,white,...,False,NaN,NaN,False,False,False,False,White - Non-Latino,False,False
276775,111643,2014-09-15,00:00:00,7100 BLOCK CASTOR AV,40.048152,-75.069087,2.0,023,24.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
276776,295845,2014-09-15,00:01:00,N 63RD ST / MASTER ST,39.972184,-75.244937,19.0,192,28.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743140,1633851,2017-12-17,23:41:00,2300 BLOCK W LEHIGH AV,39.995880,-75.169186,39.0,393,28.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1743141,1512494,2017-12-17,23:50:00,5600 BLOCK LANGDON ST,40.033320,-75.093339,2.0,21,22.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1743142,1631086,2017-12-17,23:50:00,HARVEY ST / MC CALLUM ST,40.037508,-75.179399,14.0,143,23.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1743143,1626762,2017-12-17,23:56:00,2900 BLOCK W ALLEGHENY AV,40.004672,-75.176977,39.0,393,45.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1743144,1638073,2017-12-17,23:58:00,3100 BLOCK FRANKFORD AV,39.991801,-75.112786,24.0,241,34.0,white,...,False,NaN,NaN,False,False,False,False,White - Non-Latino,False,False

In [17]:
eagles_home_gamedays.to_csv("STOPS_EAGLES_HOME_GAMES.csv", index=False)

In [20]:
data["eagles_home_game"] = mask2
data["eagles_game_home_or_away"] = mask
data

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband,eagles_home_game,eagles_game_home_or_away
0,411981,2014-01-01,01:14:00,NaN,NaN,NaN,19.0,191,31.0,black,...,True,False,True,True,False,Black - Non-Latino,True,False,False,False
1,407442,2014-01-01,01:57:00,NaN,NaN,NaN,12.0,121,21.0,black,...,False,True,True,True,False,Black - Non-Latino,False,False,False,False
2,217556,2014-01-01,03:30:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,24.0,black,...,NaN,False,False,False,False,Black - Non-Latino,False,False,False,False
3,217557,2014-01-01,03:40:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,20.0,black,...,NaN,False,False,False,False,Black - Non-Latino,False,False,False,False
4,230988,2014-01-01,08:30:00,N 56TH ST / UPLAND WAY,39.983712,-75.234188,19.0,193,31.0,black,...,NaN,False,False,False,False,Black - Non-Latino,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,1791698,2018-04-14,21:36:00,S 59TH ST / ELMWOOD AV,39.928084,-75.221956,12.0,123,60.0,black,...,NaN,False,False,False,False,Black - Non-Latino,False,False,False,False
1865092,1789312,2018-04-14,22:01:00,2600 BLOCK JUDSON ST,39.998242,-75.175190,39.0,393,33.0,asian/pacific islander,...,NaN,False,False,False,False,Asian,False,False,False,False
1865093,1791237,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,21.0,black,...,False,True,True,True,False,Black - Non-Latino,False,False,False,False
1865094,1791243,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,22.0,black,...,False,True,True,True,False,Black - Non-Latino,False,False,False,False
1865095,1791232,2018-04-14,23:10:00,200 BLOCK W LEHIGH AV,39.991461,-75.134880,25.0,253,69.0,black,...,NaN,False,False,False,False,Black - Non-Latino,False,False,False,False

In [21]:
data.to_csv("STOP_DATA.csv", index=False)

In [ ]:
def add_game_indicator_col(stop_data, game_dates, new_col_name):

    # game_dates: unique dates

    # convert col to date
    stop_data["date"] = pd.to_datetime(stop_data["date"])
    mask = stop_data["date"].isin(game_dates)
    stop_data[new_col_name] = mask

    return stop_data